version: "3.9"
services:
  php-apache:
    build:
      context: ./docker/php-apache
      args:
        - TZ=${TIMEZONE}
    image: ${COMPOSE_PROJECT_NAME}_php-apache:${APACHE_TAG}-${PHP_TAG}
    #networks:
    ports:
      - "80:80"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
  mysql:
    build: './build/mysql'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    command: mysqld --sql_mode="" --max_connections=2000
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE:${MYSQL_DATABASE_NAME}
  
volumes:
  app:
  mysql:
